package gbe

import (
	"github.com/mrlsd/go-tutor/gbe/arrays"
	"github.com/mrlsd/go-tutor/gbe/atomic-counters"
	"github.com/mrlsd/go-tutor/gbe/base64-encoding"
	"github.com/mrlsd/go-tutor/gbe/channel-buffering"
	"github.com/mrlsd/go-tutor/gbe/channel-directions"
	"github.com/mrlsd/go-tutor/gbe/channel-synchronization"
	"github.com/mrlsd/go-tutor/gbe/channels"
	"github.com/mrlsd/go-tutor/gbe/closing-channels"
	"github.com/mrlsd/go-tutor/gbe/closures"
	"github.com/mrlsd/go-tutor/gbe/collection-functions"
	"github.com/mrlsd/go-tutor/gbe/command-line-arguments"
	"github.com/mrlsd/go-tutor/gbe/command-line-flags"
	"github.com/mrlsd/go-tutor/gbe/constants"
	"github.com/mrlsd/go-tutor/gbe/defer-exec"
	"github.com/mrlsd/go-tutor/gbe/environment-variables"
	"github.com/mrlsd/go-tutor/gbe/epoch"
	"github.com/mrlsd/go-tutor/gbe/errors"
	"github.com/mrlsd/go-tutor/gbe/execing-processes"
	"github.com/mrlsd/go-tutor/gbe/exit"
	"github.com/mrlsd/go-tutor/gbe/for_loop"
	"github.com/mrlsd/go-tutor/gbe/functions"
	"github.com/mrlsd/go-tutor/gbe/goroutines"
	"github.com/mrlsd/go-tutor/gbe/hello-world"
	"github.com/mrlsd/go-tutor/gbe/if-else"
	"github.com/mrlsd/go-tutor/gbe/interfaces"
	"github.com/mrlsd/go-tutor/gbe/json"
	"github.com/mrlsd/go-tutor/gbe/line-filters"
	"github.com/mrlsd/go-tutor/gbe/maps"
	"github.com/mrlsd/go-tutor/gbe/methods"
	"github.com/mrlsd/go-tutor/gbe/multiple-return-values"
	"github.com/mrlsd/go-tutor/gbe/mutexes"
	"github.com/mrlsd/go-tutor/gbe/non-blocking-channel-operations"
	"github.com/mrlsd/go-tutor/gbe/number-parsing"
	"github.com/mrlsd/go-tutor/gbe/panic"
	"github.com/mrlsd/go-tutor/gbe/pointers"
	"github.com/mrlsd/go-tutor/gbe/random-numbers"
	"github.com/mrlsd/go-tutor/gbe/range-flow"
	"github.com/mrlsd/go-tutor/gbe/range-over-channels"
	"github.com/mrlsd/go-tutor/gbe/rate-limiting"
	"github.com/mrlsd/go-tutor/gbe/reading-files"
	"github.com/mrlsd/go-tutor/gbe/recursion"
	"github.com/mrlsd/go-tutor/gbe/regular-expressions"
	"github.com/mrlsd/go-tutor/gbe/select_go"
	"github.com/mrlsd/go-tutor/gbe/sha1-hashes"
	"github.com/mrlsd/go-tutor/gbe/signals"
	"github.com/mrlsd/go-tutor/gbe/slices"
	"github.com/mrlsd/go-tutor/gbe/sorting"
	"github.com/mrlsd/go-tutor/gbe/sorting-by-functions"
	"github.com/mrlsd/go-tutor/gbe/spawning-processes"
	"github.com/mrlsd/go-tutor/gbe/stateful-goroutines"
	"github.com/mrlsd/go-tutor/gbe/string-formatting"
	"github.com/mrlsd/go-tutor/gbe/string-functions"
	"github.com/mrlsd/go-tutor/gbe/structs"
	"github.com/mrlsd/go-tutor/gbe/switch-control"
	"github.com/mrlsd/go-tutor/gbe/tickers"
	"github.com/mrlsd/go-tutor/gbe/time-fn"
	"github.com/mrlsd/go-tutor/gbe/time-formatting-parsing"
	"github.com/mrlsd/go-tutor/gbe/timeouts"
	"github.com/mrlsd/go-tutor/gbe/timers"
	"github.com/mrlsd/go-tutor/gbe/url-parsing"
	"github.com/mrlsd/go-tutor/gbe/values"
	"github.com/mrlsd/go-tutor/gbe/variables"
	"github.com/mrlsd/go-tutor/gbe/variadic-functions"
	"github.com/mrlsd/go-tutor/gbe/worker-pools"
	"github.com/mrlsd/go-tutor/gbe/writing-files"
	"fmt"
)

func Run() {
	fmt.Println("=====\nGo by Examples:")

	hello_world.Main()
	values.Main()
	variables.Main()
	constants.Main()
	for_loop.Main()
	if_else.Main()
	switch_control.Main()
	arrays.Main()
	slices.Main()
	maps.Main()

	range_flow.Main()
	functions.Main()
	multiple_return_values.Main()
	variadic_functions.Main()
	closures.Main()
	recursion.Main()
	pointers.Main()
	structs.Main()
	methods.Main()
	interfaces.Main()

	errors.Main()
	goroutines.Main()
	channels.Main()
	channel_buffering.Main()
	channel_synchronization.Main()
	channel_directions.Main()
	select_go.Main()
	timeouts.Main()
	non_blocking_channel_operations.Main()
	closing_channels.Main()

	range_over_channels.Main()
	timers.Main()
	tickers.Main()
	worker_pools.Main()
	rate_limiting.Main()
	atomic_counters.Main()
	mutexes.Main()
	stateful_goroutines.Main()
	sorting.Main()
	sorting_by_functions.Main()

	panic.Main()
	defer_exec.Main()
	collection_functions.Main()
	string_functions.Main()
	string_formatting.Main()
	regular_expressions.Main()
	json.Main()
	time_fn.Main()
	epoch.Main()
	time_formatting_parsing.Main()

	random_numbers.Main()
	number_parsing.Main()
	url_parsing.Main()
	sha1_hashes.Main()
	base64_encoding.Main()
	reading_files.Main()
	writing_files.Main()
	line_filters.Main()
	command_line_arguments.Main()
	command_line_flags.Main()

	environment_variables.Main()
	spawning_processes.Main()
	execing_processes.Main()
	signals.Main()
	exit.Main()
}
